name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Check directory structure
      run: ls -R
    - name: Install Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.12'
    - name: build with Gradle
      working-directory: app
      run: ./gradlew build
    - name: Run checkstyle
      working-directory: app
      run: ./gradlew checkstyleMain
    - name: Run test
      working-directory: app
      run: ./gradlew test

    - name: Generate JaCoCo Report
      working-directory: app
      run: ./gradlew jacocoTestReport --rerun-tasks

        # Шаг 7: Проверка наличия отчета
    - name: Check JaCoCo Report
      working-directory: app
      run: |
           ls -l build/jacoco/test.exec
           ls -l build/reports/jacoco/test/jacocoTestReport.xml

    - name: Publish code coverage
      uses: paambaati/codeclimate-action@v9.0.0
      env:
         CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
         JACOCO_SOURCE_PATH: app/src/main/java
      with:
         coverageCommand: ${{github.workspace}}/app/gradlew jacocoTestReport --rerun-tasks
         coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco